
package drawingapp;

import javax.comm.*;
import java.lang.*;


public class portProp extends javax.swing.JFrame {

    /** Creates new form PortProperties */
    public portProp() {        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        okButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        comTypeLabel = new javax.swing.JLabel();
        timeOutLabel = new javax.swing.JLabel();
        baudLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        stopLabel = new javax.swing.JLabel();
        parityLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        comTypeTextField = new javax.swing.JTextField();
        timeOutTextField = new javax.swing.JTextField();
        baudTextField = new javax.swing.JTextField();
        dataComboBox = new javax.swing.JComboBox();
        stopComboBox = new javax.swing.JComboBox();
        parityComboBox = new javax.swing.JComboBox();
        flowLabel = new javax.swing.JLabel();
        flowComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setAlwaysOnTop(true);
        setTitle("Port properties");

        okButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("App Name");
        
        comTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comTypeLabel.setText("COM Type");

        timeOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeOutLabel.setText("Time out");

        baudLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baudLabel.setText("BaudRate");

        dataLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataLabel.setText("DataBits");

        stopLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stopLabel.setText("StopBits");

        parityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parityLabel.setText("Parity");
        
        comTypeTextField.setText("COM1");

        nameTextField.setText("Serial Comm App");

        timeOutTextField.setText("100");

        baudTextField.setText("9600");

        dataComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 DataBit Format", "6 DataBit Format", "7 DataBit Format", "8 DataBit Format" }));
        dataComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataComboBoxActionPerformed(evt);
            }
        });
        
        dataComboBox.setSelectedIndex(3);

        stopComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 StopBit", "1-1/2 StopBits", "2 StopBits" }));

        parityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Even Parity scheme", "Mark Parity scheme", "No Parity ", "Odd Parity scheme", "SPACE Parity scheme" }));
        parityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parityComboBoxActionPerformed(evt);
            }
        });
        
        parityComboBox.setSelectedIndex(2);

        flowLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        flowLabel.setText("Flow Control");

        flowComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flow Control Off", "RTS/CTS flow control on input", "RTS/CTS flow control on output", "XON/XOFF flow control on input", "XON/XOFF flow control on output" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(okButton)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comTypeLabel)
                    .addComponent(timeOutLabel)
                    .addComponent(nameLabel)
                    .addComponent(parityLabel)
                    .addComponent(dataLabel)
                    .addComponent(flowLabel)
                    .addComponent(stopLabel)
                    .addComponent(baudLabel))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(baudTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flowComboBox, 0, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stopComboBox, 0, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parityComboBox, 0, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(timeOutTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataComboBox, 0, 152, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comTypeLabel)
                    .addComponent(comTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeOutLabel)
                    .addComponent(timeOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flowLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baudLabel)
                    .addComponent(baudTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabel)
                    .addComponent(dataComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parityLabel)
                    .addComponent(parityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {

    baudRate=Integer.parseInt(baudTextField.getText());
    
    int temp=dataComboBox.getSelectedIndex();
    
    if(temp==0)
        dataBits=SerialPort.DATABITS_5;
    else if(temp==1)
        dataBits=SerialPort.DATABITS_6;
    else if(temp==2)
        dataBits=SerialPort.DATABITS_7;
    else
        dataBits=SerialPort.DATABITS_8;
    
    temp=stopComboBox.getSelectedIndex();
    
    if(temp==0)
        stopBits=SerialPort.STOPBITS_1;
    else if(temp==1)
        stopBits=SerialPort.STOPBITS_1_5;
    else
        stopBits=SerialPort.STOPBITS_2;
    
    temp=parityComboBox.getSelectedIndex();
    
    if(temp==0)
        parity=SerialPort.PARITY_EVEN;
    else if(temp==1)
        parity=SerialPort.PARITY_MARK;
    else if(temp==2)
        parity=SerialPort.PARITY_NONE;
    else if(temp==3)
        parity=SerialPort.PARITY_ODD;
    else
        parity=SerialPort.PARITY_SPACE;
    
    temp=flowComboBox.getSelectedIndex();
    
    if(temp==0)
        flowControl=SerialPort.FLOWCONTROL_NONE;
    else if(temp==1)
        flowControl=SerialPort.FLOWCONTROL_RTSCTS_IN;
    else if(temp==2)
        flowControl=SerialPort.FLOWCONTROL_RTSCTS_OUT;
    else if(temp==3)
        flowControl=SerialPort.FLOWCONTROL_XONXOFF_IN;
    else if(temp==4)
        flowControl=SerialPort.FLOWCONTROL_XONXOFF_OUT;
    
    timeOut=Integer.parseInt(timeOutTextField.getText());
    
    appName=nameTextField.getText();
    
    comType=comTypeTextField.getText();

    this.dispose();
}

private void parityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void dataComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

public int getBaudRate(){
    return baudRate;
}

public int getStopBits(){
    return stopBits;
}

public int getDataBits(){
    return dataBits;
}

public int getFlowControl(){
    return flowControl;
}

public int getParity(){
    return parity;
}

public int getTimeOut(){
    return timeOut;
}

public String getAppName(){
    return appName;
}

public String getCom(){
    return comType;
}
        

    // Variables declaration - do not modify
    private javax.swing.JLabel comTypeLabel;
    private javax.swing.JTextField comTypeTextField;
    private javax.swing.JLabel baudLabel;
    private javax.swing.JTextField baudTextField;
    private javax.swing.JComboBox dataComboBox;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JComboBox flowComboBox;
    private javax.swing.JLabel flowLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox parityComboBox;
    private javax.swing.JLabel parityLabel;
    private javax.swing.JComboBox stopComboBox;
    private javax.swing.JLabel stopLabel;
    private javax.swing.JLabel timeOutLabel;
    private javax.swing.JTextField timeOutTextField;
    // End of variables declaration
    
    private int baudRate=9600;
    private int stopBits=SerialPort.STOPBITS_1;
    private int dataBits=SerialPort.DATABITS_8;
    private int parity=SerialPort.PARITY_NONE;
    private int flowControl=SerialPort.FLOWCONTROL_NONE;
    private int timeOut=100;
    private String appName=new String("Serial Comm App");
    private String comType=new String("COM1");
}
